import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import {ReactNode} from "react";

const inter = Poppins({ subsets: ['latin'], weight: ["400", "500", "700", "900"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app', 
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
