export { createUserProfileModule } from "./composition-root";
export type { UserProfileModule } from "./composition-root";
export { ProfileService } from "./services/profile.service";
export { ProfileController } from "./controllers/profile.controller";
export { ProfileRepository } from "./repositories/profile.repository";
export type { ProfileServicePort } from "./ports/profile-service.port";
export type { ProfileRepositoryPort } from "./ports/profile-repository.port";
export type { OrgRoleQueryPort, UserOrganizationsQueryPort } from "./ports/org-query.port";
export { createProfileGuards } from "./guards/profile.guards";
export type { ProfileGuards } from "./guards/profile.guards";
